In [15]:
#statistics analysis
#z -test to check whether the data is same or not
from numpy.random import seed
from numpy.random import randn
from numpy import mean
from numpy import std

seed(10)
#generating the random numbers
A=5 * randn(100) + 50

B=5 * randn(100) + 52

print('A : mean=%.3f stdv=%.3f' % (mean(A), std(A)))
print('B : mean=%.3f stdv=%.3f' % (mean(B), std(B)))

A : mean=50.397 stdv=4.835
B : mean=52.346 stdv=4.927


In [16]:
A

array([56.65793252, 53.57639487, 42.27299854, 49.95808075, 53.10667987,
       46.3995722 , 51.32755793, 50.54274263, 50.02145715, 49.12699895,
       52.16513095, 56.01518687, 45.17467165, 55.14137039, 51.14315065,
       52.22568806, 44.31698894, 50.67568439, 57.42268501, 44.60097557,
       40.1113586 , 41.28313852, 51.33035082, 61.92483665, 55.61845627,
       58.36311107, 50.49574608, 56.98998189, 48.64376006, 53.06602092,
       48.66341406, 47.25345493, 50.66354148, 47.61928993, 56.5423654 ,
       50.9750664 , 52.00104994, 48.31183831, 56.28236132, 46.34015249,
       53.30115776, 48.24564054, 45.3028332 , 47.55331392, 45.97704429,
       48.93651181, 48.30429877, 51.56084968, 52.82576335, 49.26289871,
       49.87047332, 51.44547102, 47.30060464, 53.5408001 , 54.21112369,
       51.01790399, 61.97351832, 54.58729469, 49.43863764, 48.18909776,
       48.83908872, 47.4913555 , 55.64392577, 46.51094985, 49.59438908,
       47.3535196 , 55.23091428, 42.90721985, 48.18750408, 49.39

In [17]:
B

array([52.58737831, 42.46271556, 47.38545368, 54.34875717, 51.27816618,
       49.99930824, 50.52008074, 56.24104305, 55.53415227, 48.06365537,
       53.46470362, 49.64596374, 64.02162803, 48.30321631, 50.43585621,
       50.25559041, 49.80486882, 52.70552084, 53.3652466 , 43.90714626,
       49.13443319, 45.39776227, 58.18102663, 64.32662541, 58.91616115,
       53.73116558, 57.11258054, 52.83405134, 60.28358312, 55.33944804,
       50.85026678, 46.35224403, 48.80018698, 53.56915261, 45.8708201 ,
       50.89103432, 58.69963155, 52.14654855, 61.92692873, 59.235828  ,
       50.56185293, 45.20344713, 51.75979337, 49.5960633 , 53.88876543,
       60.07203987, 46.38447982, 50.05636027, 53.66174975, 57.67486587,
       54.55357206, 54.07148821, 58.72274712, 54.46757659, 50.81497908,
       52.28642575, 48.46464276, 54.73332419, 56.71250204, 37.10201614,
       58.09074425, 51.71739638, 54.30444226, 55.31187006, 40.52448336,
       46.02035344, 50.33449419, 48.04304615, 53.3708639 , 49.42

In [18]:
#statsmodels lib used for the ztest 
from statsmodels.stats.weightstats import ztest
#H0 : both data are same
#H1 : both are not same

In [19]:
stat,p_value=ztest(A,B) #in output the second value represent the p value

In [20]:
p_value

0.004967685420845533

In [21]:
#significance_level =0.05
#H0 == Both A and B are same
#H1== both A and B are not same
if p_value<0.05:
    print("Reject H0")
else:
    print("Accept H0")

Reject H0


In [22]:
#comparison of two groups which are different
from scipy.stats import ttest_ind
#compare samples
stat, p=ttest_ind(A,B)
print('Statistics=%.3f,p=%.3f' %(stat,p))
#interpret
alpha=0.05
if p_value<alpha:
    print("Reject H0")
else:
    print("Accept H0")

Statistics=-2.809,p=0.005
Reject H0


In [23]:
#paired students t-test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import ttest_rel
#seed the random number generator
seed(1)
#generate two independent samples
data1=5 * randn(100) + 50
data2 = 5 * randn(100) + 58
#compare sample 
stat,p=ttest_rel(data1,data2)
print('Statistics=%.3f,p=%.3f' % (stat,p))
#interpret
alpha = 0.05
if p>alpha:
    print('Same distribution (Fail to reject H0)')
else:
    print('Different distribution (reject H0)')



Statistics=-13.736,p=0.000
Different distribution (reject H0)


In [24]:
#Analysis of variance test
#the one way analaysis of variance(ANOVA) is used to determine whether there are any statistically significant distribution of three or more 
#independent (unrelated) group

#H0 : all 3 distributions are same. 
#H1 : All distributions are not same.

In [26]:
#analysis of variance test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import f_oneway
#generate the random number generator
seed(1)
#generate 3 different independent samples
data1=5 * randn(100) + 50
data2 = 5 * randn(100) + 52
data3=5 * randn(100) + 50
#compare samples
stat,p= f_oneway(data1,data2,data3)
print('Statistics=%.3f,p=%.3f' % (stat,p))
#interpret
alpha=0.05
if p>alpha:
    print("Same Distribution(fail to Reject H0)")
else:
    print("Different distributions(reject H0)")
    

Statistics=10.035,p=0.000
Different distributions(reject H0)


In [ ]:
'''Chi square test for categorical features

chi-square test used for categorical features in dataset. we calculate chi-squared between each feature and
desired number of features with best chi-square scores. it determines if the association between two categories
would reflect their real association in the population'''

In [31]:
#load libraries

from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

#load iris data
iris_dataset = load_iris()
#create features and target
X = iris_dataset.data
y = iris_dataset.target

#convert to categorical data by converting data to integers
X=X.astype(int)

#two features with highest chi-squared statistics are selected
chi2_features = SelectKBest(chi2, k=2)
X_kbest_features = chi2_features.fit_transform(X,y)

#reduced features
print('Original feature number:', X.shape[1])
print('Reduced feature number:',X_kbest_features.shape[1])


Original feature number: 4
Reduced feature number: 2


In [32]:
iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [33]:
X_kbest_features.shape

(150, 2)

In [34]:
X_kbest_features

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [4, 1],
       [4, 1],
       [4, 1],
       [4, 1],
       [4, 1],
       [4, 1],
       [4, 1],
       [3, 1],
       [4, 1],
       [3, 1],
       [3, 1],
       [4, 1],
       [4, 1],
       [4, 1],
       [3, 1],
       [4, 1],
       [4,