In [1]:
#data analysis

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
arr_1d = np.array([1,2,3])
arr_1d

array([1, 2, 3])

In [6]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
zeros=np.zeros((3,3))#zeros() used print 0
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ones=np.ones((4,4))#ones for print 1
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
random_arr = np.random.random((2,2))#random numbers 
random_arr

array([[0.11985977, 0.92139532],
       [0.22310206, 0.17919386]])

In [11]:
#identity matrix
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
range_arr= np.arange(0,10,2) #start,stop,step
range_arr

array([0, 2, 4, 6, 8])

In [13]:
#ARRAY ATTRIBUTES


In [14]:
aar=np.array([[1,2,3],[4,5,6]])
print("Shape : ",aar.shape)#rows and col
print("Size : ",aar.size)#no of elements
print("Data type:", aar.dtype)#define datatype
print("Number of dimensions : ",aar.ndim)#dimensions

Shape :  (2, 3)
Size :  6
Data type: int32
Number of dimensions :  2


In [15]:
print(aar[:,1:])


[[2 3]
 [5 6]]


In [16]:
#adding elements in list
a=[1,2,3,4]
b=[5,6,7,8]
for i in range (len(a)):
        print(a[i]+b[i],end = " ")

6 8 10 12 

In [17]:
#ARRAY OPERATORS
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a1*a2)
print(a1*2)#scaler operation

[5 7 9]
[ 4 10 18]
[2 4 6]


In [18]:
#MATRIX MULTIPLICATION
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
result= np.dot(mat1,mat2)
result

array([[19, 22],
       [43, 50]])

In [19]:
#BROADCASTING
aa= np.array([1,2,3])
bb=2
print(aa+bb)

[3 4 5]


In [20]:
#UNIVERSAL FUNCS(ufuncs)
arr=np.array([1,2,3])
#exponentiation
print(np.exp(arr))
#square root
print(np.sqrt(arr))
#logarithm
print(np.log(arr))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [21]:
#AGGREGATION FUNCS
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standrad Deviation:",np.std(arr))
print("Maximum:",np.max(arr))
print("Minimum:",np.min(arr))


Sum: 6
Mean: 2.0
Standrad Deviation: 0.816496580927726
Maximum: 3
Minimum: 1


In [22]:
#RESHAPING ARRAYS
arr1= np.array([1,2,3,4,5,6])
reshaped = arr1.reshape(2,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#STACKING AND SPLITING
A1=np.array([1,2])
A2=np.array([3,4])

#vertical stack
print(np.vstack((a,b)))
#horizontal stack
print(np.hstack((a,b)))

#splitting

arra=np.array([1,2,3,4,5,6])
#split into 3 parts
print(np.array_split(arr,3))


[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[array([1]), array([2]), array([3])]


In [24]:
#copy and view
#view share memory
ar1=np.array([1,2,3])
view=ar1.view()
view[0]=10
print(ar1)

#copy doesnot share memory
copy=ar1.copy()
copy[0]=20
print(copy)


[10  2  3]
[20  2  3]


In [48]:
#TASKS

#1.ARRAY CREATION.create a 1D array of numbers from 10 to 50.create a 3*3 array of random numbers between 0 and 1
array=np.array([10,20,30,40,50])
print(array)
array1=np.random.random((3,3))
print(array1)

#2ARRAY ATTRIBUTES .find the shape ,size,and datatype of the array you created in the perious task
array2=np.array([[1,2,3,4],[5,6,7,8]])
print("Shape : ",array2.shape)#rows and col
print("Size : ",array2.size)#no of elements
print("Data type:", array2.dtype)#define datatype
print("Number of dimensions : ",array2.ndim)#dimensions

#3BASIC OPERATIONS.add 5 to every element of a 1d array.multiply two 2 D array element wise
array2=array2+5
array2


mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
result= np.dot(mat1,mat2)
result


#4 INDEXING ANS SLICING.create a 5*5 array integers from 1 to 25
#.extract.the first row
#.the last column
#.a subarray of the three rows and first two column
a11=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a11)
print(a11[:1])
print(a11[4:])
print(a11[:3,:2])

#5.AGGREGARATION
#. CREATE a 10 elements array of random integers between 1 and 100.find
#.the max value
#.the min value
#.the mean and standard deviation
a12=np.array([11,21,31,41,51,61,71,81,82,98])
print(max(a12))
print(min(a12))
print(np.mean(a12))
print(np.std(a12))

#6.reshapping.covert a 1d array of numbers from 1 to 12 into a 3*4 matirx
a13=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a14=a13.reshape(3,4)
print(a14)

#7.BOARDCASTING
#.create a 3*3 matrix ones.add 1d array[1,2,3] to each row
a15=np.array([[1,2,3],[6,7,8],[11,12,13]])
a16=np.array([1,2,3])
print(a15+a16)
#8.FILTERING
#.create a 1D array of random integers between 1 and 50 ,extract all elemnts that are divisible by 5
a17=np.array([1,4,5,7,9,10,15,19,20,25,35,45])
for i in range (len(a17)):
    if a17[i]%5==0:
        print(a17[i],end = " ")

#9.MATRIX MULTIPLICATION.CREATE two 2*2 matrices and perform matix multiplication
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
result= np.dot(mat1,mat2)
print(result)

#10.ADVANCE INDEXING
#.GIVEN a 4*4 array,use fancy indexing to extract the diagonal elements
a18=np.array([[1,2,3,4],[6,7,8,9],[11,12,13,14],[16,17,18,19]])
for i in range (4):
    for j in range (4):
        if a18[i][j] == a18[j][i]:
            print(a18[i][j])
                


[10 20 30 40 50]
[[0.20212541 0.07933892 0.23239022]
 [0.80565501 0.88928367 0.96211896]
 [0.04494321 0.29090536 0.62216717]]
Shape :  (2, 4)
Size :  8
Data type: int32
Number of dimensions :  2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[1 2 3 4 5]]
[[21 22 23 24 25]]
[[ 1  2]
 [ 6  7]
 [11 12]]
98
11
54.8
27.249954128401757
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4  6]
 [ 7  9 11]
 [12 14 16]]
5 10 15 20 25 35 45 [[19 22]
 [43 50]]
1
7
13
19
